# (c) ECOLE POLYTECHNIQUE FEDERALE DE LAUSANNE, Switzerland, VPSI, 2017-2018.
# See the LICENSE file for more details.

language: node_js
node_js:
  - "8"

before_script:
  - "echo '{\"username\":\"\",\"password\":\"\"}' > secret.json"
